/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot") version "3.5.7"
    id("io.spring.dependency-management") version "1.1.7"
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency libraries that are used by the application.
    implementation(libs.guava)
    implementation("org.springframework.boot:spring-boot-starter-data-jpa") //this is for JPA DB model tags handling
    implementation("org.springframework.boot:spring-boot-starter-web") //this is for web based 
    testImplementation("org.springframework.boot:spring-boot-starter-test") //this command is for commandline application
    //this is for development only for automatic restart, live reload support, disable template caching, smarter classpath handling
    developmentOnly("org.springframework.boot:spring-boot-devtools") 
    implementation("org.json:json:20250517") //For JSON Processing
    //Database
    implementation("org.hibernate.orm:hibernate-community-dialects:6.2.7.Final") //SQL Lite Hibernate 
    runtimeOnly("org.xerial:sqlite-jdbc:3.42.0.0") //Only to create sqlite during runtime
    testRuntimeOnly("com.h2database:h2") //In memory DB to run during test cases only
    // JUnit 5
    testImplementation("org.junit.jupiter:junit-jupiter:5.12.1") 
    // Mockito core
    testImplementation("org.mockito:mockito-core:5.5.0")
    // Mockito + JUnit 5 integration
    testImplementation("org.mockito:mockito-junit-jupiter:5.5.0")
    // Optional: Kotlin test helpers
    testImplementation(kotlin("test"))
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.12.1")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    //mainClass = "org.application.CommandlineApp"
    mainClass = "org.application.WebApp"
}
