/*
 * This source file was generated by the Gradle 'init' task
 */
package org.application;

//Unit Test Dependencies
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
//Built in JAVA class Dependencies
import java.util.List;
import java.util.Optional;
import java.util.UUID;
//Own Implementation Dependencies
import org.application.model.Student;
import org.application.repository.StudentRepository;
import org.application.serviceimplementation.StudentServiceImplementation;

@ExtendWith(MockitoExtension.class)
class StudentServiceTest {

    @Mock
    private StudentRepository studentRepository; 

    @InjectMocks
    private StudentServiceImplementation studentService;

    @Test 
    void testGetStudentList() {
        //Create a List with to contain the entry
        List<Student> studentsMockList = List.of(new Student("Mira","CEEM900")); 
        when(studentRepository.findAll()).thenReturn(studentsMockList); // To say , when studentRepository is called return the list
        //Call the service that is being tested
        List<Student> testRunResult = studentService.listAllStudents();
        //Check if value is similar
        assertEquals("Mira", testRunResult.get(0).getFullname());
        assertEquals("CEEM900", testRunResult.get(0).getCourseId());
    }

    @Test
    void testaddNewStudent(){
        Student testStudent = new Student("Mira", "CEEM900");
        when(studentRepository.save(Mockito.any(Student.class))).thenReturn(testStudent);
        String testRunResult = studentService.addNewStudent(testStudent);
        verify(studentRepository, times(1)).save(Mockito.any(Student.class));
        assertEquals("SYSTEM API LOG: successfully run addNewStudent(Student student)", testRunResult);
    }

    @Test
    void testDeleteStudentService(){
        UUID uuid = UUID.fromString("3c5b9235-4ceb-4c3d-907f-695779cc87e0");
        Student student = new Student("Mira", "CEEM900");
        Optional<Student> testStudent = Optional.of(student);
        when(studentRepository.findById(Mockito.any(UUID.class))).thenReturn(testStudent);
        //studentRepository.delete(Mockito.any(Student.class)) <--- You don't have to mock delete because delete is a void type and Mockito ignore void
        String testRunResult = studentService.deleteStudentService(uuid);
        verify(studentRepository, times(1)).delete(student);
        assertEquals(
      "SYSTEM API LOG: At deleteStudent(Student student) - Deleted Student",
                testRunResult
        );
    }

    @Test
    void getStudentById(){
        UUID uuid = UUID.fromString("3c5b9235-4ceb-4c3d-907f-695779cc87e0");
        Student student = new Student("Mira", "CEEM900");
        Optional<Student> testStudent = Optional.of(student);
        when(studentRepository.findById(Mockito.any(UUID.class))).thenReturn(testStudent);
        Optional<Student> testRunResult = studentService.getStudentById(uuid);;
        assertTrue(testRunResult.isPresent());
        assertEquals("Mira", testRunResult.get().getFullname());
        assertEquals("CEEM900", testRunResult.get().getCourseId());
    }
}
